extends: ["A-Bekar/labelsync-test:.github/labels-global.yml", "A-Bekar/labelsync-test:.github/labels-test.yml"]
labels:
  - name: testing
    description: "Leak-proof bottles for travel-sized toiletries."
    color: ab4ccc
  - name: chore
    color: 87f775
  - name: enhancement
    description: "Fun and colorful gardening tools designed for children."
    color: 08ad46
  - name: chore
    description: "Collapsible travel bowl for pets on the go."
    color: 98e2ac
